name = "clawbotlist"
compatibility_date = "2026-02-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "clawbotlist-db"
database_id = "6049aec7-efae-4015-9e1a-c68169981d30"
